apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flowops-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kareem-Waled/flowops-platform.git
    targetRevision: main
    path: k8s/manifests/production
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
